os: linux
language: c
compiler:
  - gcc

dist:
  - bionic

sudo: true

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y libssl-dev python-all python3-all uuid-dev openssl
  - sudo pip install paho-mqtt
  - sudo ln -s /usr/bin/gcc-9 /usr/local/bin/gcc
  - export CC=/usr/bin/gcc-9
  - cmake .

script:
  - gcc -Wall -Wunused -Werror -Wextra -Wno-unused-result -pedantic -std=c11 -O3 -D_DEFAULT_SOURCE -lpthread -lssl -lcrypto -lcrypt src/*.c -o sol
  - gcc -Wall -Wunused -Werror -Wextra -Wno-unused-result -pedantic -std=c11 -O3 -D_DEFAULT_SOURCE -lpthread -lssl -lcrypto -lcrypt src/hashtable.c src/bst.c src/config.c src/list.c src/trie.c src/util.c src/iterator.c tests/*.c -o sol_test
  - ./sol_test
  - python3 tests/integration/run.py

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
    packages:
      - gcc-9
