os: linux
language: c
compiler: gcc

dist: bionic

sudo: true

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y libssl-dev python-all python3-all openssl
  - sudo pip install paho-mqtt
  - cmake .

script:
  - make
  - python3 tests/integration/run.py
