os: linux
language: c
compiler:
  - gcc

dist:
  - bionic

sudo: true

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y libdevel libssl-dev python-all python3-all uuid-dev openssl
  - sudo pip install paho-mqtt
  - cmake .

script: make
